'use client'

import { useState, useRef, useEffect } from 'react'
import { Send, Loader2, Bot, User, Sparkles } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Textarea } from '@/components/ui/textarea'
import { cn } from '@/lib/utils'

interface Message {
  role: 'user' | 'assistant'
  content: string
  timestamp: Date
}

interface ChatPanelProps {
  department: string
  clientId?: string
  templateId?: string
  templateVariables?: Record<string, string>
  documentId?: string
  onContentGenerated?: (content: string) => void
  initialGenerate?: boolean
  initialPrompt?: string
}

export function ChatPanel({
  department,
  clientId,
  templateId,
  templateVariables,
  documentId,
  onContentGenerated,
  initialGenerate = false,
  initialPrompt,
}: ChatPanelProps) {
  const [messages, setMessages] = useState<Message[]>([])
  const [input, setInput] = useState('')
  const [isLoading, setIsLoading] = useState(false)
  const messagesEndRef = useRef<HTMLDivElement>(null)
  const hasAutoGenerated = useRef(false)

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' })
  }, [messages])

  useEffect(() => {
    if (initialGenerate && initialPrompt && !hasAutoGenerated.current) {
      hasAutoGenerated.current = true
      sendMessage(initialPrompt)
    }
  }, [initialGenerate, initialPrompt])

  async function sendMessage(content?: string) {
    const messageContent = content || input.trim()
    if (!messageContent || isLoading) return

    const userMessage: Message = {
      role: 'user',
      content: messageContent,
      timestamp: new Date(),
    }

    const newMessages = [...messages, userMessage]
    setMessages(newMessages)
    setInput('')
    setIsLoading(true)

    try {
      const res = await fetch('/api/claude', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          messages: newMessages.map((m) => ({ role: m.role, content: m.content })),
          department,
          clientId: clientId || null,
          templateId: templateId || null,
          templateVariables: templateVariables || null,
          documentId: documentId || null,
          mode: templateId ? 'generate' : 'chat',
        }),
      })

      const data = await res.json()

      if (!res.ok) {
        throw new Error(data.error || 'API isteği başarısız')
      }

      const assistantMessage: Message = {
        role: 'assistant',
        content: data.content,
        timestamp: new Date(),
      }
      setMessages((prev) => [...prev, assistantMessage])

      if (onContentGenerated && data.content) {
        onContentGenerated(markdownToHtml(data.content))
      }
    } catch (err) {
      const errorMsg = err instanceof Error ? err.message : 'Bir hata oluştu'
      setMessages((prev) => [
        ...prev,
        { role: 'assistant', content: `Hata: ${errorMsg}`, timestamp: new Date() },
      ])
    } finally {
      setIsLoading(false)
    }
  }

  function handleKeyDown(e: React.KeyboardEvent) {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault()
      sendMessage()
    }
  }

  const quickPrompts = [
    'Bu içeriği daha kısa yap',
    'Daha resmi bir dil kullan',
    'Başlığı güçlendir',
    'Giriş paragrafını yeniden yaz',
  ]

  return (
    <div className="flex flex-col h-full bg-gray-50">
      {/* Mesajlar */}
      <div className="flex-1 overflow-y-auto p-4 space-y-4">
        {messages.length === 0 && !isLoading && (
          <div className="text-center py-8">
            <div className="w-12 h-12 bg-[#E87722]/10 rounded-full flex items-center justify-center mx-auto mb-3">
              <Sparkles className="w-6 h-6 text-[#E87722]" />
            </div>
            <p className="text-gray-500 text-sm font-medium">AI Asistan</p>
            <p className="text-gray-400 text-xs mt-1">Bir şeyler sorun veya içerik üretin</p>
          </div>
        )}

        {messages.map((message, idx) => (
          <div
            key={idx}
            className={cn(
              'flex gap-2',
              message.role === 'user' ? 'flex-row-reverse' : 'flex-row'
            )}
          >
            <div
              className={cn(
                'w-7 h-7 rounded-full flex items-center justify-center shrink-0 mt-0.5',
                message.role === 'user'
                  ? 'bg-[#1B2A4A]'
                  : 'bg-[#E87722]'
              )}
            >
              {message.role === 'user' ? (
                <User className="w-3.5 h-3.5 text-white" />
              ) : (
                <Bot className="w-3.5 h-3.5 text-white" />
              )}
            </div>
            <div
              className={cn(
                'max-w-[85%] rounded-xl px-3 py-2 text-sm',
                message.role === 'user'
                  ? 'bg-[#1B2A4A] text-white'
                  : 'bg-white border border-gray-200 text-gray-700'
              )}
            >
              <pre className="whitespace-pre-wrap font-sans text-sm">{message.content}</pre>
            </div>
          </div>
        ))}

        {/* Yükleniyor göstergesi */}
        {isLoading && (
          <div className="flex gap-2">
            <div className="w-7 h-7 rounded-full bg-[#E87722] flex items-center justify-center shrink-0 mt-0.5">
              <Bot className="w-3.5 h-3.5 text-white" />
            </div>
            <div className="max-w-[85%] bg-white border border-gray-200 rounded-xl px-3 py-2 text-sm text-gray-700">
              <div className="flex items-center gap-2">
                <Loader2 className="w-3.5 h-3.5 animate-spin text-[#E87722]" />
                <span className="text-gray-400">Düşünüyor...</span>
              </div>
            </div>
          </div>
        )}

        <div ref={messagesEndRef} />
      </div>

      {/* Hızlı öneriler */}
      {messages.length > 0 && !isLoading && (
        <div className="px-3 py-2 flex gap-1.5 flex-wrap border-t border-gray-200 bg-white">
          {quickPrompts.map((prompt) => (
            <button
              key={prompt}
              onClick={() => sendMessage(prompt)}
              className="text-xs px-2 py-1 bg-gray-100 hover:bg-gray-200 text-gray-600 rounded-full transition-colors"
            >
              {prompt}
            </button>
          ))}
        </div>
      )}

      {/* Input */}
      <div className="p-3 border-t border-gray-200 bg-white">
        <div className="flex gap-2">
          <Textarea
            placeholder="Mesaj yazın... (Enter ile gönder)"
            value={input}
            onChange={(e) => setInput(e.target.value)}
            onKeyDown={handleKeyDown}
            disabled={isLoading}
            className="text-sm resize-none min-h-[60px] max-h-32"
            rows={2}
          />
          <Button
            variant="orange"
            size="icon"
            onClick={() => sendMessage()}
            disabled={isLoading || !input.trim()}
            className="shrink-0 self-end h-9 w-9"
          >
            {isLoading ? (
              <Loader2 className="w-4 h-4 animate-spin" />
            ) : (
              <Send className="w-4 h-4" />
            )}
          </Button>
        </div>
      </div>
    </div>
  )
}

// Basit Markdown → HTML dönüşümü
function markdownToHtml(markdown: string): string {
  return markdown
    .replace(/^# (.*)/gm, '<h1>$1</h1>')
    .replace(/^## (.*)/gm, '<h2>$1</h2>')
    .replace(/^### (.*)/gm, '<h3>$1</h3>')
    .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
    .replace(/\*(.*?)\*/g, '<em>$1</em>')
    .replace(/^- (.*)/gm, '<li>$1</li>')
    .replace(/(<li>[\s\S]*?<\/li>)/gm, '<ul>$1</ul>')
    .replace(/^\d+\. (.*)/gm, '<li>$1</li>')
    .replace(/\n\n/g, '</p><p>')
    .replace(/^(?!<[h|u|o|l])/gm, '')
    .split('\n')
    .filter(Boolean)
    .map((line) => {
      if (line.startsWith('<h') || line.startsWith('<ul') || line.startsWith('<ol') || line.startsWith('<li')) {
        return line
      }
      return `<p>${line}</p>`
    })
    .join('\n')
}
