'use client'

import { useState, useRef, useEffect } from 'react'
import { Send, Loader2, Bot, User, Sparkles } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Textarea } from '@/components/ui/textarea'
import { cn } from '@/lib/utils'

interface Message {
  role: 'user' | 'assistant'
  content: string
  timestamp: Date
}

interface ChatPanelProps {
  department: string
  clientId?: string
  templateId?: string
  templateVariables?: Record<string, string>
  documentId?: string
  onContentGenerated?: (content: string) => void
  initialGenerate?: boolean
  initialPrompt?: string
}

export function ChatPanel({
  department,
  clientId,
  templateId,
  templateVariables,
  documentId,
  onContentGenerated,
  initialGenerate = false,
  initialPrompt,
}: ChatPanelProps) {
  const [messages, setMessages] = useState<Message[]>([])
  const [input, setInput] = useState('')
  const [isLoading, setIsLoading] = useState(false)
  const messagesEndRef = useRef<HTMLDivElement>(null)
  const hasAutoGenerated = useRef(false)

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' })
  }, [messages])

  useEffect(() => {
    if (initialGenerate && initialPrompt && !hasAutoGenerated.current) {
      hasAutoGenerated.current = true
      sendMessage(initialPrompt)
    }
  }, [initialGenerate, initialPrompt])

  async function sendMessage(content?: string) {
    const messageContent = content || input.trim()
    if (!messageContent || isLoading) return

    const userMessage: Message = {
      role: 'user',
      content: messageContent,
      timestamp: new Date(),
    }

    const newMessages = [...messages, userMessage]
    setMessages(newMessages)
    setInput('')
    setIsLoading(true)

    try {
      const res = await fetch('/api/claude', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          messages: newMessages.map((m) => ({ role: m.role, content: m.content })),
          department,
          clientId: clientId || null,
          templateId: templateId || null,
          templateVariables: templateVariables || null,
          documentId: documentId || null,
          mode: templateId ? 'generate' : 'chat',
        }),
      })

      const data = await res.json()

      if (!res.ok) {
        throw new Error(data.error || 'API isteği başarısız')
      }

      const assistantMessage: Message = {
        role: 'assistant',
        content: data.content,
        timestamp: new Date(),
      }
      setMessages((prev) => [...prev, assistantMessage])

      if (onContentGenerated && data.content) {
        onContentGenerated(markdownToHtml(data.content))
      }
    } catch (err) {
      const errorMsg = err instanceof Error ? err.message : 'Bir hata oluştu'
      setMessages((prev) => [
        ...prev,
        { role: 'assistant', content: `Hata: ${errorMsg}`, timestamp: new Date() },
      ])
    } finally {
      setIsLoading(false)
    }
  }

  function handleKeyDown(e: React.KeyboardEvent) {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault()
      sendMessage()
    }
  }

  const quickPrompts = [
    'Bu içeriği daha kısa yap',
    'Daha resmi bir dil kullan',
    'Başlığı güçlendir',
    'Giriş paragrafını yeniden yaz',
  ]

  return (
    <div className="flex flex-col h-full bg-gray-50">
      {/* Mesajlar */}
      <div className="flex-1 overflow-y-auto p-4 space-y-4">
        {messages.length === 0 && !isLoading && (
          <div className="text-center py-8">
            <div className="w-12 h-12 bg-[#E87722]/10 rounded-full flex items-center justify-center mx-auto mb-3">
              <Sparkles className="w-6 h-6 text-[#E87722]" />
            </div>
            <p className="text-gray-500 text-sm font-medium">AI Asistan</p>
            <p className="text-gray-400 text-xs mt-1">Bir şeyler sorun veya içerik üretin</p>
          </div>
        )}

        {messages.map((message, idx) => (
          <div
            key={idx}
            className={cn(
              'flex gap-2',
              message.role === 'user' ? 'flex-row-reverse' : 'flex-row'
            )}
          >
            <div
              className={cn(
                'w-7 h-7 rounded-full flex items-center justify-center shrink-0 mt-0.5',
                message.role === 'user'
                  ? 'bg-[#1B2A4A]'
                  : 'bg-[#E87722]'
              )}
            >
              {message.role === 'user' ? (
                <User className="w-3.5 h-3.5 text-white" />
              ) : (
                <Bot className="w-3.5 h-3.5 text-white" />
              )}
            </div>
            <div
              className={cn(
                'max-w-[85%] rounded-xl px-3 py-2 text-sm',
                message.role === 'user'
                  ? 'bg-[#1B2A4A] text-white'
                  : 'bg-white border border-gray-200 text-gray-700'
              )}
            >
              <pre className="whitespace-pre-wrap font-sans text-sm">{message.content}</pre>
            </div>
          </div>
        ))}

        {/* Yükleniyor göstergesi */}
        {isLoading && (
          <div className="flex gap-2">
            <div className="w-7 h-7 rounded-full bg-[#E87722] flex items-center justify-center shrink-0 mt-0.5">
              <Bot className="w-3.5 h-3.5 text-white" />
            </div>
            <div className="max-w-[85%] bg-white border border-gray-200 rounded-xl px-3 py-2 text-sm text-gray-700">
              <div className="flex items-center gap-2">
                <Loader2 className="w-3.5 h-3.5 animate-spin text-[#E87722]" />
                <span className="text-gray-400">Düşünüyor...</span>
              </div>
            </div>
          </div>
        )}

        <div ref={messagesEndRef} />
      </div>

      {/* Hızlı öneriler */}
      {messages.length > 0 && !isLoading && (
        <div className="px-3 py-2 flex gap-1.5 flex-wrap border-t border-gray-200 bg-white">
          {quickPrompts.map((prompt) => (
            <button
              key={prompt}
              onClick={() => sendMessage(prompt)}
              className="text-xs px-2 py-1 bg-gray-100 hover:bg-gray-200 text-gray-600 rounded-full transition-colors"
            >
              {prompt}
            </button>
          ))}
        </div>
      )}

      {/* Input */}
      <div className="p-3 border-t border-gray-200 bg-white">
        <div className="flex gap-2">
          <Textarea
            placeholder="Mesaj yazın... (Enter ile gönder)"
            value={input}
            onChange={(e) => setInput(e.target.value)}
            onKeyDown={handleKeyDown}
            disabled={isLoading}
            className="text-sm resize-none min-h-[60px] max-h-32"
            rows={2}
          />
          <Button
            variant="orange"
            size="icon"
            onClick={() => sendMessage()}
            disabled={isLoading || !input.trim()}
            className="shrink-0 self-end h-9 w-9"
          >
            {isLoading ? (
              <Loader2 className="w-4 h-4 animate-spin" />
            ) : (
              <Send className="w-4 h-4" />
            )}
          </Button>
        </div>
      </div>
    </div>
  )
}

// Basit Markdown → HTML dönüşümü — kendi parser'ımız (marked kütüphanesi client'da çalışmıyor)
function markdownToHtml(markdown: string): string {
  let html = markdown

  // Tablolar (önce işle)
  html = html.replace(/^(\|.+\|)\n(\|[-:\s|]+\|)\n((?:\|.+\|\n?)*)/gm, (_match, header: string, _sep: string, body: string) => {
    const headerCells = header.split('|').filter((c: string) => c.trim()).map((c: string) => `<th style="padding:8px 12px;background:#1B2A4A;color:white;font-weight:600;text-align:left;border:1px solid #e5e7eb">${c.trim()}</th>`)
    const rows = body.trim().split('\n').map((row: string) => {
      const cells = row.split('|').filter((c: string) => c.trim()).map((c: string) => `<td style="padding:8px 12px;border:1px solid #e5e7eb">${c.trim()}</td>`)
      return `<tr>${cells.join('')}</tr>`
    })
    return `<table style="width:100%;border-collapse:collapse;margin:16px 0"><thead><tr>${headerCells.join('')}</tr></thead><tbody>${rows.join('')}</tbody></table>`
  })

  // Başlıklar
  html = html.replace(/^### (.*)/gm, '<h3>$1</h3>')
  html = html.replace(/^## (.*)/gm, '<h2>$1</h2>')
  html = html.replace(/^# (.*)/gm, '<h1>$1</h1>')

  // Bold ve italic
  html = html.replace(/\*\*\*(.*?)\*\*\*/g, '<strong><em>$1</em></strong>')
  html = html.replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
  html = html.replace(/\*(.*?)\*/g, '<em>$1</em>')

  // Yatay çizgi
  html = html.replace(/^---$/gm, '<hr>')

  // Sıralı liste
  html = html.replace(/^(\d+)\. (.*)/gm, '<ol-item>$2</ol-item>')
  html = html.replace(/((?:<ol-item>.*<\/ol-item>\n?)+)/g, (_match, items: string) => {
    const lis = items.replace(/<ol-item>(.*?)<\/ol-item>/g, '<li>$1</li>')
    return `<ol>${lis}</ol>`
  })

  // Sırasız liste
  html = html.replace(/^[-*] (.*)/gm, '<ul-item>$1</ul-item>')
  html = html.replace(/((?:<ul-item>.*<\/ul-item>\n?)+)/g, (_match, items: string) => {
    const lis = items.replace(/<ul-item>(.*?)<\/ul-item>/g, '<li>$1</li>')
    return `<ul>${lis}</ul>`
  })

  // Paragraflar — boş satırlarla ayrılmış metin bloklarını <p> ile sar
  const blocks = html.split(/\n\n+/)
  html = blocks.map(block => {
    const trimmed = block.trim()
    if (!trimmed) return ''
    if (trimmed.startsWith('<h') || trimmed.startsWith('<table') || trimmed.startsWith('<ul') ||
        trimmed.startsWith('<ol') || trimmed.startsWith('<hr')) {
      return trimmed
    }
    // Tek satır içindeki \n'leri <br> ile değiştir
    return `<p>${trimmed.replace(/\n/g, '<br>')}</p>`
  }).filter(Boolean).join('\n')

  return html
}
